### ISSUE TITLE
Some DataManagers need to be order dependent

### ISSUE THREAD

**Issue by jzuech3** [NextThought/nti.transactions#10]
Some DataManagers(transactional operations) need to run only after other DataManagers have executed completely (for example, redis queues relying on database state).

Transactional data managers are ordered by the 'str' value returned by a sortKey function on the data manager.  These cases (where transactional operations are order dependent) are probably rare, so a 'best-effort' at ensuring these operations occur after others should be acceptable.

**Comment by jamadden** [comment]
Fixed by #11.
