### ISSUE TITLE
Break ZODB dependency

### ISSUE THREAD

**Issue by jamadden** [NextThought/nti.transactions#2]
Currently, we have a dependency on ZODB. This is _only_ to turn an unexpected `TypeError` into a `ZODB.POSException.StorageError`. Otherwise,  we're completely independent of it.

I propose that we define our own custom subclass of `transaction.interfaces.TransactionError` and raise that instead.

Our application has a custom Pyramid exception view for StorageError, `ZODBStorageErrorExceptionView` (to which we can easily add this new class), but as far as I can see that's the only use of StorageError in our codebase.

**Comment by jamadden** [comment]
Any thoughts or objections? @papachoco @jzuech3

**Comment by papachoco** [comment]
Sounds good to me
