### ISSUE TITLE
Pyramid tween: Exception views are broken since Pyramid 1.9

### ISSUE THREAD

**Issue by jamadden** [NextThought/nti.transactions#49]
At some point, exception views apparently began re-invoking the tweens *without* unwinding them. It's possible this was 
[in Pyramid 1.9](https://docs.pylonsproject.org/projects/pyramid/en/latest/whatsnew-1.9.html):

> Pyramid's default execution policy will attempt to handle and render uncaught exceptions. This is a subtle, but fundamental, change indicating that an exception view may expect to be called outside of the default EXCVIEW tween.

This means that an unhandled exception (of some kinds? Seems to depend on...something) is likely to raise an `AlreadyInTransaction` error as this tween is re-entered. (Note: The change in 1.9 has been reverted for 2.0.)

```python traceback
File '///eggs/pyramid-1.10.4-py2.7.egg/pyramid/router.py', line 270 in __call__
  response = self.execution_policy(environ, self)
File '///eggs/pyramid-1.10.4-py2.7.egg/pyramid/router.py', line 279 in default_execution_policy
  return request.invoke_exception_view(reraise=True)
File '///eggs/pyramid-1.10.4-py2.7.egg/pyramid/view.py', line 778 in invoke_exception_view
  reraise_(*exc_info)
File '///eggs/pyramid-1.10.4-py2.7.egg/pyramid/router.py', line 277 in default_execution_policy
  return router.invoke_request(request)
File '///eggs/pyramid-1.10.4-py2.7.egg/pyramid/router.py', line 249 in invoke_request
  response = handle_request(request)
File '///sources/nti.dataserver/src/nti/appserver/tweens/performance.py', line 117 in __call__
  response = self.handler(request)
File '///eggs/pyramid-1.10.4-py2.7.egg/pyramid/tweens.py', line 43 in excview_tween
  response = _error_handler(request, exc)
File '///eggs/pyramid-1.10.4-py2.7.egg/pyramid/tweens.py', line 17 in _error_handler
  reraise(*exc_info)
File '///eggs/pyramid-1.10.4-py2.7.egg/pyramid/tweens.py', line 41 in excview_tween
  response = handler(request)
...
File '///eggs/nti.transactions-4.0.0-py2.7.egg/nti/transactions/pyramid_tween.py', line 277 in __call__
  result = TransactionLoop.__call__(self, request)  # not super() for speed
File '///eggs/nti.transactions-4.0.0-py2.7.egg/nti/transactions/loop.py', line 460 in __call__
  return self.__loop(txm, note, stats, args, kwargs)
File '///eggs/nti.transactions-4.0.0-py2.7.egg/nti/transactions/loop.py', line 485 in __loop
  tx = begin()
File '///eggs/transaction-3.0.0-py2.7.egg/transaction/_manager.py', line 78 in begin
  raise AlreadyInTransaction()
AlreadyInTransaction:
```

I need to understand the exact circumstances of how this happens and then fix it.

/cc @jzuech3

**Comment by jamadden** [comment]
The stacktrace is somewhat hard to understand, with all the `reraise` in there and the burying of any related exceptions.

I'm not finding any evidence of tweens being reentered. 

One thing we do know: When I saw a flood of these, it happened at the same time we were expecting to generate lots of other errors that should (and did) bubble out to a middleware. But for some reason, many requests also generated this error to the middleware.

It makes no sense because we're using gunicorn+gevent, and each request is handled in its own new greenlet, which means a fresh transaction manager (because its thread/greenlet local).

I suppose a bug in gevent's thread-local is possible, where when one greenlet gets allocated at the same spot as a previous one we wind up using old thread-locals. But at that point the transaction manager should be without a transaction.

**Comment by jamadden** [comment]
> I suppose a bug in gevent's thread-local is possible, where when one greenlet gets allocated at the same spot as a previous one we wind up using old thread-locals

I'm pretty confident it's not that. I was able to follow the logging of a single request through some retries, then ultimately an OperationalError from the database driver, then an AlreadyInTransaction error. All in the same greenlet.

**Comment by jamadden** [comment]
Got it. It's a bug, or a bad interaction, in the underlying `transaction` library itself. 

Transaction synchronizers are called from `transaction.begin()`. If one of those raises an exception, the TransactionManager goes to a bad state: It thinks it has begun a transaction, but the error will propagate out of `begin()`. That will break the loop from cleaning up the half-open transaction.

In this case, the ZODB Connection is open, and as such is a registered synchronizer. It polls the storage for invalidations at synch time, and that throws an exception. Part of the fix would be to put the ZODB connection tween *under* the transaction tween, not above it — this is faster too (or would be if our ZODB connection tween wasn't cheating). That in itself would fix the problems we're seeing. Unfortunately, that's not possible, because you can't close a connection joined to a transaction.

At least in this scenario, it does look like we're reusing the same greenlet for multiple requests, and I think I understand how that's possible: HTTP Keep-Alive/pipelining.

Without being able to move the connection tween,  part of the fix here would be to try to rollback the transaction if beginning it throws an exception. The rest of the fix is to actually make `transaction` do that itself.

**Comment by jamadden** [comment]
> At least in this scenario, it does look like we're reusing the same greenlet for multiple requests, and I think I understand how that's possible: HTTP Keep-Alive/pipelining.

And maybe look into forcing the HTTP connection to close if we have an exception? This is done by setting the `Connection: close` header in the headers when calling `start_response()`.

**Comment by jzuech3** [comment]
Nice find! What kind of exceptions were occurring in `transaction.begin()`?

**Comment by jamadden** [comment]
In all the most recent cases, I’m pretty confident it was the database connection errors. In the one or two earlier examples, I don’t have enough info to be sure, but I think they also happened at times of stress, so something similar seems likely.

**Comment by jamadden** [comment]
> And maybe look into forcing the HTTP connection to close if we have an exception?

The pyramid tween can't do that, at least not in our configuration. The uncaught exception bubbles up to the Paste errormiddleware, which calls `start_response(status, headers, exc_info)` itself, passing in the complete set of headers. We'd need to override `start_response` in our handler class to watch for `exc_info` that isn't none and add to the headers.

**Comment by jamadden** [comment]
4.0.1 is on PyPI.
